export const Films = [
    {
      "id": "1",
      "image": "assets/images/id1.jpg",
      "title": "Logan",
      "genre": "Action",
      "time":65791,
      "year": "2017",
      "nation": "USA",
      "info": "Logan has the distinction of being one of the first R-rated movies to ever be added to Disney+. It also happens to be a truly great superhero film that serves as a worthy swan song for X-Men stars Hugh Jackman and Patrick Stewart. Decades after the X-Men were at their prime, Logan (Jackman) is a broken man with failing powers who struggles to care for Professor Xavier (Stewart), whose own powers are proving to be lethal for those around him. Logan just wants to find a place where they can disappear. But when he is called upon to escort a young mutant girl named Laura (Dafne Keen), Logan learns that there is more to the fall of the mutants than he initially believed. And it may not be within his ability to protect Laura and the few remaining mutants from the forces aligned against them.",
      "trailer": "https://www.youtube.com/embed/Div0iP65aZo",
    },
    {
      "id": "2",
      "image": "assets/images/id2.jpg",
      "title": "Joker ",
      "genre": "Action",
      "time":65791,
      "year": "2019",
      "nation": "USA",
      "info": "There is an argument to be made that Joker doesn’t belong anywhere on a list of superhero movies. Even director Todd Phillips told Empire Magazine that he didn’t see his film as a comic book movie. But the story unfolds in Gotham City, Bruce Wayne and his parents are in it, and the protagonist evolves into perhaps the most iconic supervillain in all pop culture. So, you know, we feel pretty confident including it. There are plenty of valid criticisms of Joker, including its depictions of mental illness and race, plus the cinematic conversation it has with films like The King of Comedy and Taxi Driver, which some argue misses the mark of homage and simply steals unapologetically. And when it was released, many questioned the timing, as it came in the wake of several mass shootings committed in the U.S. — some feel that perhaps that wasn’t the time to glorify an antihero like Arthur Fleck.But in terms of a movie that does find itself in the superhero neighborhood whether Phillips likes it or not, what Joker does better than any other film is show us exactly how someone could shed their humanity to become a supervillain. Sure, we’ve had plenty of sympathetic supervillains before, like Tom Hiddleston’s Loki and Michael B. Jordan’s Killmonger, but in Joker, we see the process unfold. We see Fleck transform into a monster, and we see it in a world just like our own that has nothing to do with rainbow bridges or vibranium meteorites.",
      "trailer": "https://www.youtube.com/embed/zAGVQLHvwOY",
    },
    {
      "id": "3",
      "image": "assets/images/id3.jpg",
      "title": "The Godfather",
      "genre": "Drama",
      "time":65791,
      "year": "1972",
      "nation": "USA",
      "info": "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
      "trailer": "https://www.youtube.com/embed/sY1S34973zA",
    },
    {
      "id": "4",
      "image": "assets/images/id4.jpg",
      "title": "Pulp Fiction",
      "genre": "Drama",
      "time":65791,
      "year": "1994",
      "nation": "USA",
      "info": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      "trailer": "https://www.youtube.com/embed/s7EdQ4FqbhY",
    },
    {
      "id": "5",
      "image": "assets/images/id5.jpg",
      "title": "The Dark Knight",
      "genre": "Adventure",
      "time":65791,
      "year": "2008",
      "nation": "USA",
      "info": "If you were to watch Christopher Nolan’s The Dark Knight without knowing anything beforehand about the cast or the plot, you would not recognize Heath Ledger as the Joker. His transformation into Batman’s clown-faced nemesis is just that good. He was so committed to the role he insisted co-star Christian Bale hit him for real in their amazing interrogation room scene, and it’s that commitment and Ledger’s talent that makes him the best reason to watch The Dark Knight. He’s so good that Aaron Eckhart’s equally dark transformation from hero District Attorney Harvey Dent into the monstrous Two-Face is often forgotten in discussions of what is unquestionably the best of Nolan’s Dark Knight trilogy.",
      "trailer": "https://www.youtube.com/embed/EXeTwQWrcwY",
    },
    {
      "id": "6",
      "image": "assets/images/id6.jpg",
      "title": "12 Angry Men",
      "genre": "Adventure",
      "time":65791,
      "year": "1957",
      "nation": "USA",
      "info": "The film tells the story of a jury of 12 men as they deliberate the conviction or acquittal of a teenager charged with murder on the basis of reasonable doubt; disagreement and conflict among them force the jurors to question their morals and values.",
      "trailer": "https://www.youtube.com/embed/TEN-2uTi2c0",
    },
    {
      "id": "7",
      "image": "assets/images/id7.jpg",
      "title": "The Lion King",
      "genre": "Drama",
      "time":65791,
      "year" : "1994",
      "nation": "USA",
      "info": "Set in a kingdom of lions in Africa, The Lion King tells the story of Simba (Swahili for lion), a lion cub who is to succeed his father, Mufasa, as King of the Pride Lands; however, after his paternal uncle Scar kills Mufasa to seize the throne, Simba is tricked into believing he was responsible for his father's death ...",
      "trailer": "https://www.youtube.com/embed/4CbLXeGSDxg",
    },
    {
      "id": "8",
      "image": "assets/images/id8.jpg",
      "title": "The Matrix",
      "genre": "Adventure",
      "time":65791,
      "year": "1999",
      "nation": "USA",
      "info": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
      "trailer": "https://www.youtube.com/embed/vKQi3bBA1y8",
    },
    {
      "id": "9",
      "image": "assets/images/id9.jpg",
      "title": "Forrest Gump",
      "genre": "Romance",
      "time":65791,
      "year": "1994",
      "nation": "USA",
      "info": "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
      "trailer": "https://www.youtube.com/embed/bLvqoHBptjg",
    },
];
